<?php
/**
 * @package     Joomla.Site
 * @subpackage  Templates.ItaliaPA
 *
 * @version     __DEPLOY_VERSION__
 *
 * @author      Helios Ciancio <info (at) eshiol (dot) it>
 * @link        https://www.eshiol.it
 * @copyright   Copyright (C) 2017 - 2022 Helios Ciancio. All rights reserved
 * @license     http://www.gnu.org/licenses/gpl-3.0.html GNU/GPL v3
 * Template ItaliaPA is free software. This version may have been modified
 * pursuant to the GNU General Public License, and as distributed it includes
 * or is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

defined('_JEXEC') or die;
?>
<div class="Carousel-item Grid Hero Hero-<?php echo $this->item->id; ?>">
	<div class="Grid-cell u-sizeFull">
		<?php
			if (JPluginHelper::getPlugin('system', 'fields'))
			{
				foreach ($this->item->jcfields as $jcField)
				{
					if (($jcField->name == 'image-heronews') && $jcField->rawvalue)
					{
						JFactory::getDocument()->addStyleDeclaration(
								".Hero-" . $this->item->id . " {background-image: url('" . JUri::root(true) . '/' . htmlspecialchars($jcField->rawvalue, ENT_COMPAT, 'UTF-8') . "') !important;}"
								);
					}
				}
			}
		?>
		<div class="Hero-content">
			<?php if ($this->item->params->get('show_category')) : ?>
				<p class="u-padding-r-bottom u-padding-r-top u-text-r-xs">
					<?php $title = $this->escape($this->item->category_title); ?>
					<span class="Dot u-background-60"></span>
					<?php if ($this->item->params->get('link_category') && $this->item->catslug) : ?>
						<a class="u-textClean u-color-60 u-text-h4" href="<?php echo JRoute::_(ContentHelperRoute::getCategoryRoute($this->item->catslug)); ?>" itemprop="genre"><?php echo $title; ?></a>
					<?php else : ?>
						<span itemprop="genre"><?php echo $title; ?></span>
					<?php endif; ?>
				</p>
			<?php endif; ?>
			<?php if ($this->item->params->get('show_title')) : ?>
				<h2 class="u-text-h2" itemprop="headline">
				<?php if ($this->item->params->get('link_titles') && $this->item->params->get('access-view')) : ?>
					<a class="u-color-95 u-textClean" href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>" itemprop="url">
						<?php echo $this->escape($this->item->title); ?>
					</a>
				<?php else : ?>
					<?php echo $this->escape($this->item->title); ?>
				<?php endif; ?>
				</h2>
			<?php endif; ?>
			<?php if (!$this->item->params->get('show_intro')) : ?>
				<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
				<?php echo $this->item->event->afterDisplayTitle; ?>
			<?php endif; ?>
			<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
			<?php echo $this->item->event->beforeDisplayContent; ?>
			<div class="u-padding-r-bottom u-padding-r-top u-text-p u-margin-r-bottom">
				<?php echo $this->item->introtext; ?>
			</div>
			<?php if (count(JModuleHelper::getModules('news'))) : ?>
				<a href="#news" class="js-scrollTo u-linkClean Button Button--info u-text-r-xs">
					<?php echo JText::_('TPL_ITALIAPA_NEWSANDEVENTS'); ?>
					<span class="u-padding-r-left Icon Icon-expand"></span></a>
			<?php endif; ?>
		</div>
	</div>
</div>