<?php
/**
 * @package		Joomla.Site
 * @subpackage	Templates.ItaliaPA
 *
 * @author		Helios Ciancio <info (at) eshiol (dot) it>
 * @link		http://www.eshiol.it
 * @copyright	Copyright (C) 2017 - 2020 Helios Ciancio. All Rights Reserved
 * @license		http://www.gnu.org/licenses/gpl-3.0.html GNU/GPL v3
 * Template ItaliaPA is free software. This version may have been modified
 * pursuant to the GNU General Public License, and as distributed it includes
 * or is derivative of works licensed under the GNU General Public License or
 * other free or open source software licenses.
 */

defined('_JEXEC') or die;

JHtml::addIncludePath(JPATH_COMPONENT . '/helpers');

JHtml::_('behavior.caption');
?>
<section <?php echo ($this->pageclass_sfx ? 'class="'.$this->pageclass_sfx.'" ' : ''); ?>itemscope itemtype="https://schema.org/Blog">
	<div class="Hero">
	<?php
	if ($this->lead_items) :
		$item = $this->lead_items[0];
		$images = json_decode($item->images);
		$document = JFactory::getDocument();
		$style = ".Hero {background-image: url('".htmlspecialchars($images->image_intro, ENT_COMPAT, 'UTF-8')."') !important;}";
		$document->addStyleDeclaration($style);
	?>
		<div class="Hero-content">
		<?php if ($item->params->get('show_category')) : ?>
			<p class="u-padding-r-bottom u-padding-r-top u-text-r-xs">
				<?php $title = $this->escape($item->category_title); ?>
				<span class="Dot u-background-60"></span>
				<?php if ($item->params->get('link_category') && $item->catslug) : ?>
				<a class="u-textClean u-color-60 u-text-h4" href="<?php echo JRoute::_(ContentHelperRoute::getCategoryRoute($item->catslug)); ?>" itemprop="genre"><?php echo $title; ?></a>
				<?php else : ?>
				<span itemprop="genre"><?php echo $title; ?></span>
				<?php endif; ?>
			</p>
		<?php endif; ?>
		<?php if ($item->params->get('show_title')) : ?>
			<h2 class="u-text-h2" itemprop="headline">
			<?php if ($item->params->get('link_titles') && $item->params->get('access-view')) : ?>
				<a class="u-color-95 u-textClean" href="<?php echo JRoute::_(ContentHelperRoute::getArticleRoute($item->slug, $item->catid, $item->language)); ?>" itemprop="url">
					<?php echo $this->escape($item->title); ?>
				</a>
			<?php else : ?>
				<?php echo $this->escape($item->title); ?>
			<?php endif; ?>
			</h2>
		<?php endif; ?>
			<?php if (!$item->params->get('show_intro')) : ?>
				<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
				<?php echo $item->event->afterDisplayTitle; ?>
			<?php endif; ?>
			<?php // Content is generated by content plugin event "onContentBeforeDisplay" ?>
			<?php echo $item->event->beforeDisplayContent; ?>
			<div class="u-padding-r-bottom u-padding-r-top u-text-p u-margin-r-bottom">
			<?php echo $item->introtext; ?>
			</div>
			<?php if (count(JModuleHelper::getModules('news'))) : ?>
			<a href="#news" class="js-scrollTo u-linkClean Button Button--info u-text-r-xs">
				<?php echo JText::_('TPL_ITALIAPA_NEWSANDEVENTS'); ?>
				<span class="u-padding-r-left Icon Icon-expand"></span></a>
			<?php endif; ?>
		</div>
	<?php endif; ?>
	</div>

	<?php if ($this->params->def('show_pagination', 2) == 1  || ($this->params->get('show_pagination') == 2 && $this->pagination->pagesTotal > 1)) : ?>
		<?php echo $this->pagination->getPagesLinks(); ?>
	<?php endif; ?>
</section>
